#!/usr/bin/env node
/**
 * Vendors the meshoptimizer decoder as a classic browser-global script at
 * public/babylon/meshopt_decoder.js, so Babylon's EXT_meshopt_compression
 * path decodes our optimized GLBs from same-origin instead of the Babylon
 * CDN (docs/world-design-plan.md, Batch B: "decoders never touch the CDN").
 *
 * The npm `meshoptimizer` package ships only ESM/CJS builds; Babylon's
 * MeshoptCompression loads its decoder via a classic <script> that must set
 * a global `MeshoptDecoder`. This transform turns the ESM export into that
 * global. The decoder embeds its WASM inline (base64), so the vendored file
 * needs no further network access.
 *
 * Re-run after bumping meshoptimizer:  node scripts/vendor_meshopt_decoder.mjs
 *   --check   CI mode: regenerate in memory and fail if the committed file
 *             differs from the installed meshoptimizer version (a dep bump
 *             without re-vendoring would otherwise ship a mismatched decoder).
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const require = createRequire(import.meta.url);
const pkgDir = dirname(require.resolve('meshoptimizer')); // package.json is blocked by exports
const pkg = JSON.parse(await readFile(join(pkgDir, 'package.json'), 'utf8'));
const src = join(pkgDir, 'meshopt_decoder.mjs');
const outDir = join(ROOT, 'public/babylon');
const outFile = join(outDir, 'meshopt_decoder.js');

let code = await readFile(src, 'utf8');
if (!code.includes('export { MeshoptDecoder };')) {
  console.error('Unexpected meshopt_decoder.mjs shape — export line not found. Aborting.');
  process.exit(1);
}
// ESM export → classic browser global (top-level `var MeshoptDecoder` is
// already function-scoped in a classic script; assign explicitly so it is
// reachable as window.MeshoptDecoder / self.MeshoptDecoder regardless).
code = code.replace(
  'export { MeshoptDecoder };',
  '(typeof self !== "undefined" ? self : globalThis).MeshoptDecoder = MeshoptDecoder;',
);
// Provenance header pins the source version so drift is visible in the diff.
const header =
  `// VENDORED — generated by scripts/vendor_meshopt_decoder.mjs from\n` +
  `// meshoptimizer@${pkg.version} (MIT). Do not edit by hand. Self-hosted so\n` +
  `// Babylon’s EXT_meshopt_compression decoder loads same-origin.\n`;
const expected = header + code;

if (CHECK) {
  const current = existsSync(outFile) ? await readFile(outFile, 'utf8') : '';
  if (current !== expected) {
    console.error(`✗ ${outFile} is stale vs meshoptimizer@${pkg.version} — run \`node scripts/vendor_meshopt_decoder.mjs\`.`);
    process.exit(1);
  }
  console.log(`✓ vendored meshopt decoder matches meshoptimizer@${pkg.version}.`);
} else {
  await mkdir(outDir, { recursive: true });
  await writeFile(outFile, expected);
  console.log(`Vendored meshopt decoder → ${outFile} (meshoptimizer@${pkg.version}, ${expected.length / 1024 | 0} KB)`);
}
